### ISSUE TITLE
App crashes when no camera is available

### ISSUE THREAD

**Issue by brunofalmeida** [b-almeida/CossetteNavigation-Android#7]
The application crashes when there are no cameras available on the device (e.g. in an emulator).

The code in `CameraActivity` (mostly in `setCamera()`) assumes that `Camera.open()` returns a camera object and `mCamera` is not `null`. However, `mCamera` may be `null` if there are no cameras available.

To fix this, methods in `CameraActivity` should check if `mCamera` is `null`.

**Comment by jacobjinkelly** [comment]
i just shoved everything into the try catch block it works when you deny permissions
